#!/bin/bash
#
#   useage:
#   mysql-iniset key value
#
#   sets my ini key to value
#   if no value is supplied key will be commented
#   If value is supplied key will automatically be commented out
#
key=$1
val=$2
scope=${3:-apache2}

filepath="/etc/mysql/conf.d/mysqldump.cnf"

if [ -f $filepath ]
then
    if [ -e $val ]
    then
        #disable if value is empty
        sudo sed -i "/^$key =.*$/s/^/;/g" $filepath

        #confirm disabled
        grep "^;$key " $filepath

    else
        #enable if value has been supplied
        sudo sed -i "/^;$key =.*$/s/^;//g" $filepath

        #modify value
        sudo sed -i "s,^$key =.*$,$key = $val," $filepath

        #confirm value
        grep "^$key " $filepath
    fi

else
    echo "$path does not exist"
fi

service mysql reload
service mysql restart
